const admin = require('firebase-admin');
// const serviceAccount = require('./path/to/your/serviceAccountKey.json');
const serviceAccount = require('./serviceAccountKey.json')

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

const shows = [
  {
    showId: 'show1',
    classicSeats: [
      { row: 'A', number: 1, price: 170 },
      { row: 'A', number: 2, price: 170 },
      // Add more classic seats
      { row: 'A', number: 3, price: 170 },
        { row: 'A', number: 4, price: 170 },
        { row: 'A', number: 5, price: 170 },
        { row: 'A', number: 6, price: 170 },
        { row: 'A', number: 7, price: 170 },
        { row: 'A', number: 8, price: 170 },
        { row: 'A', number: 9, price: 170 },
        { row: 'A', number: 10, price: 170 },

        // Add more classic seats here
        { row: 'B', number: 1, price: 170 },
        { row: 'B', number: 2, price: 170 },
        { row: 'B', number: 3, price: 170 },
        { row: 'B', number: 4, price: 170 },
        { row: 'B', number: 5, price: 170 },
        { row: 'B', number: 6, price: 170 },
        { row: 'B', number: 7, price: 170 },
        { row: 'B', number: 8, price: 170 },
        { row: 'B', number: 9, price: 170 },
        { row: 'B', number: 10, price: 170 },
        // Add more classic seats here

        { row: 'C', number: 1, price: 170 },
        { row: 'C', number: 2, price: 170 },
        { row: 'C', number: 3, price: 170 },
        { row: 'C', number: 4, price: 170 },
        { row: 'C', number: 5, price: 170 },
        { row: 'C', number: 6, price: 170 },
        { row: 'C', number: 7, price: 170 },
        { row: 'C', number: 8, price: 170 },
        { row: 'C', number: 9, price: 170 },
        { row: 'C', number: 10, price: 170 },
    ],
    primeSeats: [
      { row: 'E', number: 1, price: 210 },
      { row: 'E', number: 2, price: 210 },
      // Add more prime seats
      { row: 'E', number: 3, price: 210 },
        { row: 'E', number: 4, price: 210 },
        { row: 'E', number: 5, price: 210 },
        { row: 'E', number: 6, price: 210 },
        { row: 'E', number: 7, price: 210 },
        { row: 'E', number: 8, price: 210 },
        { row: 'E', number: 9, price: 210 },
        { row: 'E', number: 10, price: 210 },
        // Add more prime seats here
        { row: 'F', number: 1, price: 210 },
        { row: 'F', number: 2, price: 210 },
        { row: 'F', number: 3, price: 210 },
        { row: 'F', number: 4, price: 210 },
        { row: 'F', number: 5, price: 210 },
        { row: 'F', number: 6, price: 210 },
        { row: 'F', number: 7, price: 210 },
        { row: 'F', number: 8, price: 210 },
        { row: 'F', number: 9, price: 210 },
        { row: 'F', number: 10, price: 210 },
        // Add more prime seats here
        { row: 'G', number: 1, price: 210 },
        { row: 'G', number: 2, price: 210 },
        { row: 'G', number: 3, price: 210 },
        { row: 'G', number: 4, price: 210 },
        { row: 'G', number: 5, price: 210 },
        { row: 'G', number: 6, price: 210 },
        { row: 'G', number: 7, price: 210 },
        { row: 'G', number: 8, price: 210 },
        { row: 'G', number: 9, price: 210 },
        { row: 'G', number: 10, price: 210 },

        { row: 'H', number: 1, price: 210 },
        { row: 'H', number: 2, price: 210 },
        { row: 'H', number: 3, price: 210 },
        { row: 'H', number: 4, price: 210 },
        { row: 'H', number: 5, price: 210 },
        { row: 'H', number: 6, price: 210 },
        { row: 'H', number: 7, price: 210 },
        { row: 'H', number: 8, price: 210 },
        { row: 'H', number: 9, price: 210 },
        { row: 'H', number: 10, price: 210 },

        { row: 'J', number: 1, price: 210 },
        { row: 'J', number: 2, price: 210 },
        { row: 'J', number: 3, price: 210 },
        { row: 'J', number: 4, price: 210 },
        { row: 'J', number: 5, price: 210 },
        { row: 'J', number: 6, price: 210 },
        { row: 'J', number: 7, price: 210 },
        { row: 'J', number: 8, price: 210 },
        { row: 'J', number: 9, price: 210 },
        { row: 'J', number: 10, price: 210 },

        { row: 'K', number: 1, price: 210 },
        { row: 'K', number: 2, price: 210 },
        { row: 'K', number: 3, price: 210 },
        { row: 'K', number: 4, price: 210 },
        { row: 'K', number: 5, price: 210 },
        { row: 'K', number: 6, price: 210 },
        { row: 'K', number: 7, price: 210 },
        { row: 'K', number: 8, price: 210 },
        { row: 'K', number: 9, price: 210 },
        { row: 'K', number: 10, price: 210 },
    ]
  },
  {
    showId: 'show2',
    classicSeats: [
        { row: 'A', number: 1, price: 170 },
        { row: 'A', number: 2, price: 170 },
        // Add more classic seats
        { row: 'A', number: 3, price: 170 },
          { row: 'A', number: 4, price: 170 },
          { row: 'A', number: 5, price: 170 },
          { row: 'A', number: 6, price: 170 },
          { row: 'A', number: 7, price: 170 },
          { row: 'A', number: 8, price: 170 },
          { row: 'A', number: 9, price: 170 },
          { row: 'A', number: 10, price: 170 },
  
          // Add more classic seats here
          { row: 'B', number: 1, price: 170 },
          { row: 'B', number: 2, price: 170 },
          { row: 'B', number: 3, price: 170 },
          { row: 'B', number: 4, price: 170 },
          { row: 'B', number: 5, price: 170 },
          { row: 'B', number: 6, price: 170 },
          { row: 'B', number: 7, price: 170 },
          { row: 'B', number: 8, price: 170 },
          { row: 'B', number: 9, price: 170 },
          { row: 'B', number: 10, price: 170 },
          // Add more classic seats here
  
          { row: 'C', number: 1, price: 170 },
          { row: 'C', number: 2, price: 170 },
          { row: 'C', number: 3, price: 170 },
          { row: 'C', number: 4, price: 170 },
          { row: 'C', number: 5, price: 170 },
          { row: 'C', number: 6, price: 170 },
          { row: 'C', number: 7, price: 170 },
          { row: 'C', number: 8, price: 170 },
          { row: 'C', number: 9, price: 170 },
          { row: 'C', number: 10, price: 170 },
      ],
      primeSeats: [
        { row: 'E', number: 1, price: 210 },
        { row: 'E', number: 2, price: 210 },
        // Add more prime seats
        { row: 'E', number: 3, price: 210 },
          { row: 'E', number: 4, price: 210 },
          { row: 'E', number: 5, price: 210 },
          { row: 'E', number: 6, price: 210 },
          { row: 'E', number: 7, price: 210 },
          { row: 'E', number: 8, price: 210 },
          { row: 'E', number: 9, price: 210 },
          { row: 'E', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'F', number: 1, price: 210 },
          { row: 'F', number: 2, price: 210 },
          { row: 'F', number: 3, price: 210 },
          { row: 'F', number: 4, price: 210 },
          { row: 'F', number: 5, price: 210 },
          { row: 'F', number: 6, price: 210 },
          { row: 'F', number: 7, price: 210 },
          { row: 'F', number: 8, price: 210 },
          { row: 'F', number: 9, price: 210 },
          { row: 'F', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'G', number: 1, price: 210 },
          { row: 'G', number: 2, price: 210 },
          { row: 'G', number: 3, price: 210 },
          { row: 'G', number: 4, price: 210 },
          { row: 'G', number: 5, price: 210 },
          { row: 'G', number: 6, price: 210 },
          { row: 'G', number: 7, price: 210 },
          { row: 'G', number: 8, price: 210 },
          { row: 'G', number: 9, price: 210 },
          { row: 'G', number: 10, price: 210 },
  
          { row: 'H', number: 1, price: 210 },
          { row: 'H', number: 2, price: 210 },
          { row: 'H', number: 3, price: 210 },
          { row: 'H', number: 4, price: 210 },
          { row: 'H', number: 5, price: 210 },
          { row: 'H', number: 6, price: 210 },
          { row: 'H', number: 7, price: 210 },
          { row: 'H', number: 8, price: 210 },
          { row: 'H', number: 9, price: 210 },
          { row: 'H', number: 10, price: 210 },
  
          { row: 'J', number: 1, price: 210 },
          { row: 'J', number: 2, price: 210 },
          { row: 'J', number: 3, price: 210 },
          { row: 'J', number: 4, price: 210 },
          { row: 'J', number: 5, price: 210 },
          { row: 'J', number: 6, price: 210 },
          { row: 'J', number: 7, price: 210 },
          { row: 'J', number: 8, price: 210 },
          { row: 'J', number: 9, price: 210 },
          { row: 'J', number: 10, price: 210 },
  
          { row: 'K', number: 1, price: 210 },
          { row: 'K', number: 2, price: 210 },
          { row: 'K', number: 3, price: 210 },
          { row: 'K', number: 4, price: 210 },
          { row: 'K', number: 5, price: 210 },
          { row: 'K', number: 6, price: 210 },
          { row: 'K', number: 7, price: 210 },
          { row: 'K', number: 8, price: 210 },
          { row: 'K', number: 9, price: 210 },
          { row: 'K', number: 10, price: 210 },
      ]
  },
  // Add more shows

  {
    showId: 'show3',
    classicSeats: [
        { row: 'A', number: 1, price: 170 },
        { row: 'A', number: 2, price: 170 },
        // Add more classic seats
        { row: 'A', number: 3, price: 170 },
          { row: 'A', number: 4, price: 170 },
          { row: 'A', number: 5, price: 170 },
          { row: 'A', number: 6, price: 170 },
          { row: 'A', number: 7, price: 170 },
          { row: 'A', number: 8, price: 170 },
          { row: 'A', number: 9, price: 170 },
          { row: 'A', number: 10, price: 170 },
  
          // Add more classic seats here
          { row: 'B', number: 1, price: 170 },
          { row: 'B', number: 2, price: 170 },
          { row: 'B', number: 3, price: 170 },
          { row: 'B', number: 4, price: 170 },
          { row: 'B', number: 5, price: 170 },
          { row: 'B', number: 6, price: 170 },
          { row: 'B', number: 7, price: 170 },
          { row: 'B', number: 8, price: 170 },
          { row: 'B', number: 9, price: 170 },
          { row: 'B', number: 10, price: 170 },
          // Add more classic seats here
  
          { row: 'C', number: 1, price: 170 },
          { row: 'C', number: 2, price: 170 },
          { row: 'C', number: 3, price: 170 },
          { row: 'C', number: 4, price: 170 },
          { row: 'C', number: 5, price: 170 },
          { row: 'C', number: 6, price: 170 },
          { row: 'C', number: 7, price: 170 },
          { row: 'C', number: 8, price: 170 },
          { row: 'C', number: 9, price: 170 },
          { row: 'C', number: 10, price: 170 },
      ],
      primeSeats: [
        { row: 'E', number: 1, price: 210 },
        { row: 'E', number: 2, price: 210 },
        // Add more prime seats
        { row: 'E', number: 3, price: 210 },
          { row: 'E', number: 4, price: 210 },
          { row: 'E', number: 5, price: 210 },
          { row: 'E', number: 6, price: 210 },
          { row: 'E', number: 7, price: 210 },
          { row: 'E', number: 8, price: 210 },
          { row: 'E', number: 9, price: 210 },
          { row: 'E', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'F', number: 1, price: 210 },
          { row: 'F', number: 2, price: 210 },
          { row: 'F', number: 3, price: 210 },
          { row: 'F', number: 4, price: 210 },
          { row: 'F', number: 5, price: 210 },
          { row: 'F', number: 6, price: 210 },
          { row: 'F', number: 7, price: 210 },
          { row: 'F', number: 8, price: 210 },
          { row: 'F', number: 9, price: 210 },
          { row: 'F', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'G', number: 1, price: 210 },
          { row: 'G', number: 2, price: 210 },
          { row: 'G', number: 3, price: 210 },
          { row: 'G', number: 4, price: 210 },
          { row: 'G', number: 5, price: 210 },
          { row: 'G', number: 6, price: 210 },
          { row: 'G', number: 7, price: 210 },
          { row: 'G', number: 8, price: 210 },
          { row: 'G', number: 9, price: 210 },
          { row: 'G', number: 10, price: 210 },
  
          { row: 'H', number: 1, price: 210 },
          { row: 'H', number: 2, price: 210 },
          { row: 'H', number: 3, price: 210 },
          { row: 'H', number: 4, price: 210 },
          { row: 'H', number: 5, price: 210 },
          { row: 'H', number: 6, price: 210 },
          { row: 'H', number: 7, price: 210 },
          { row: 'H', number: 8, price: 210 },
          { row: 'H', number: 9, price: 210 },
          { row: 'H', number: 10, price: 210 },
  
          { row: 'J', number: 1, price: 210 },
          { row: 'J', number: 2, price: 210 },
          { row: 'J', number: 3, price: 210 },
          { row: 'J', number: 4, price: 210 },
          { row: 'J', number: 5, price: 210 },
          { row: 'J', number: 6, price: 210 },
          { row: 'J', number: 7, price: 210 },
          { row: 'J', number: 8, price: 210 },
          { row: 'J', number: 9, price: 210 },
          { row: 'J', number: 10, price: 210 },
  
          { row: 'K', number: 1, price: 210 },
          { row: 'K', number: 2, price: 210 },
          { row: 'K', number: 3, price: 210 },
          { row: 'K', number: 4, price: 210 },
          { row: 'K', number: 5, price: 210 },
          { row: 'K', number: 6, price: 210 },
          { row: 'K', number: 7, price: 210 },
          { row: 'K', number: 8, price: 210 },
          { row: 'K', number: 9, price: 210 },
          { row: 'K', number: 10, price: 210 },
      ]
  },


  {
    showId: 'show4',
    classicSeats: [
        { row: 'A', number: 1, price: 170 },
        { row: 'A', number: 2, price: 170 },
        // Add more classic seats
        { row: 'A', number: 3, price: 170 },
          { row: 'A', number: 4, price: 170 },
          { row: 'A', number: 5, price: 170 },
          { row: 'A', number: 6, price: 170 },
          { row: 'A', number: 7, price: 170 },
          { row: 'A', number: 8, price: 170 },
          { row: 'A', number: 9, price: 170 },
          { row: 'A', number: 10, price: 170 },
  
          // Add more classic seats here
          { row: 'B', number: 1, price: 170 },
          { row: 'B', number: 2, price: 170 },
          { row: 'B', number: 3, price: 170 },
          { row: 'B', number: 4, price: 170 },
          { row: 'B', number: 5, price: 170 },
          { row: 'B', number: 6, price: 170 },
          { row: 'B', number: 7, price: 170 },
          { row: 'B', number: 8, price: 170 },
          { row: 'B', number: 9, price: 170 },
          { row: 'B', number: 10, price: 170 },
          // Add more classic seats here
  
          { row: 'C', number: 1, price: 170 },
          { row: 'C', number: 2, price: 170 },
          { row: 'C', number: 3, price: 170 },
          { row: 'C', number: 4, price: 170 },
          { row: 'C', number: 5, price: 170 },
          { row: 'C', number: 6, price: 170 },
          { row: 'C', number: 7, price: 170 },
          { row: 'C', number: 8, price: 170 },
          { row: 'C', number: 9, price: 170 },
          { row: 'C', number: 10, price: 170 },
      ],
      primeSeats: [
        { row: 'E', number: 1, price: 210 },
        { row: 'E', number: 2, price: 210 },
        // Add more prime seats
        { row: 'E', number: 3, price: 210 },
          { row: 'E', number: 4, price: 210 },
          { row: 'E', number: 5, price: 210 },
          { row: 'E', number: 6, price: 210 },
          { row: 'E', number: 7, price: 210 },
          { row: 'E', number: 8, price: 210 },
          { row: 'E', number: 9, price: 210 },
          { row: 'E', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'F', number: 1, price: 210 },
          { row: 'F', number: 2, price: 210 },
          { row: 'F', number: 3, price: 210 },
          { row: 'F', number: 4, price: 210 },
          { row: 'F', number: 5, price: 210 },
          { row: 'F', number: 6, price: 210 },
          { row: 'F', number: 7, price: 210 },
          { row: 'F', number: 8, price: 210 },
          { row: 'F', number: 9, price: 210 },
          { row: 'F', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'G', number: 1, price: 210 },
          { row: 'G', number: 2, price: 210 },
          { row: 'G', number: 3, price: 210 },
          { row: 'G', number: 4, price: 210 },
          { row: 'G', number: 5, price: 210 },
          { row: 'G', number: 6, price: 210 },
          { row: 'G', number: 7, price: 210 },
          { row: 'G', number: 8, price: 210 },
          { row: 'G', number: 9, price: 210 },
          { row: 'G', number: 10, price: 210 },
  
          { row: 'H', number: 1, price: 210 },
          { row: 'H', number: 2, price: 210 },
          { row: 'H', number: 3, price: 210 },
          { row: 'H', number: 4, price: 210 },
          { row: 'H', number: 5, price: 210 },
          { row: 'H', number: 6, price: 210 },
          { row: 'H', number: 7, price: 210 },
          { row: 'H', number: 8, price: 210 },
          { row: 'H', number: 9, price: 210 },
          { row: 'H', number: 10, price: 210 },
  
          { row: 'J', number: 1, price: 210 },
          { row: 'J', number: 2, price: 210 },
          { row: 'J', number: 3, price: 210 },
          { row: 'J', number: 4, price: 210 },
          { row: 'J', number: 5, price: 210 },
          { row: 'J', number: 6, price: 210 },
          { row: 'J', number: 7, price: 210 },
          { row: 'J', number: 8, price: 210 },
          { row: 'J', number: 9, price: 210 },
          { row: 'J', number: 10, price: 210 },
  
          { row: 'K', number: 1, price: 210 },
          { row: 'K', number: 2, price: 210 },
          { row: 'K', number: 3, price: 210 },
          { row: 'K', number: 4, price: 210 },
          { row: 'K', number: 5, price: 210 },
          { row: 'K', number: 6, price: 210 },
          { row: 'K', number: 7, price: 210 },
          { row: 'K', number: 8, price: 210 },
          { row: 'K', number: 9, price: 210 },
          { row: 'K', number: 10, price: 210 },
      ]
  },




  {
    showId: 'show5',
    classicSeats: [
        { row: 'A', number: 1, price: 170 },
        { row: 'A', number: 2, price: 170 },
        // Add more classic seats
        { row: 'A', number: 3, price: 170 },
          { row: 'A', number: 4, price: 170 },
          { row: 'A', number: 5, price: 170 },
          { row: 'A', number: 6, price: 170 },
          { row: 'A', number: 7, price: 170 },
          { row: 'A', number: 8, price: 170 },
          { row: 'A', number: 9, price: 170 },
          { row: 'A', number: 10, price: 170 },
  
          // Add more classic seats here
          { row: 'B', number: 1, price: 170 },
          { row: 'B', number: 2, price: 170 },
          { row: 'B', number: 3, price: 170 },
          { row: 'B', number: 4, price: 170 },
          { row: 'B', number: 5, price: 170 },
          { row: 'B', number: 6, price: 170 },
          { row: 'B', number: 7, price: 170 },
          { row: 'B', number: 8, price: 170 },
          { row: 'B', number: 9, price: 170 },
          { row: 'B', number: 10, price: 170 },
          // Add more classic seats here
  
          { row: 'C', number: 1, price: 170 },
          { row: 'C', number: 2, price: 170 },
          { row: 'C', number: 3, price: 170 },
          { row: 'C', number: 4, price: 170 },
          { row: 'C', number: 5, price: 170 },
          { row: 'C', number: 6, price: 170 },
          { row: 'C', number: 7, price: 170 },
          { row: 'C', number: 8, price: 170 },
          { row: 'C', number: 9, price: 170 },
          { row: 'C', number: 10, price: 170 },
      ],
      primeSeats: [
        { row: 'E', number: 1, price: 210 },
        { row: 'E', number: 2, price: 210 },
        // Add more prime seats
        { row: 'E', number: 3, price: 210 },
          { row: 'E', number: 4, price: 210 },
          { row: 'E', number: 5, price: 210 },
          { row: 'E', number: 6, price: 210 },
          { row: 'E', number: 7, price: 210 },
          { row: 'E', number: 8, price: 210 },
          { row: 'E', number: 9, price: 210 },
          { row: 'E', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'F', number: 1, price: 210 },
          { row: 'F', number: 2, price: 210 },
          { row: 'F', number: 3, price: 210 },
          { row: 'F', number: 4, price: 210 },
          { row: 'F', number: 5, price: 210 },
          { row: 'F', number: 6, price: 210 },
          { row: 'F', number: 7, price: 210 },
          { row: 'F', number: 8, price: 210 },
          { row: 'F', number: 9, price: 210 },
          { row: 'F', number: 10, price: 210 },
          // Add more prime seats here
          { row: 'G', number: 1, price: 210 },
          { row: 'G', number: 2, price: 210 },
          { row: 'G', number: 3, price: 210 },
          { row: 'G', number: 4, price: 210 },
          { row: 'G', number: 5, price: 210 },
          { row: 'G', number: 6, price: 210 },
          { row: 'G', number: 7, price: 210 },
          { row: 'G', number: 8, price: 210 },
          { row: 'G', number: 9, price: 210 },
          { row: 'G', number: 10, price: 210 },
  
          { row: 'H', number: 1, price: 210 },
          { row: 'H', number: 2, price: 210 },
          { row: 'H', number: 3, price: 210 },
          { row: 'H', number: 4, price: 210 },
          { row: 'H', number: 5, price: 210 },
          { row: 'H', number: 6, price: 210 },
          { row: 'H', number: 7, price: 210 },
          { row: 'H', number: 8, price: 210 },
          { row: 'H', number: 9, price: 210 },
          { row: 'H', number: 10, price: 210 },
  
          { row: 'J', number: 1, price: 210 },
          { row: 'J', number: 2, price: 210 },
          { row: 'J', number: 3, price: 210 },
          { row: 'J', number: 4, price: 210 },
          { row: 'J', number: 5, price: 210 },
          { row: 'J', number: 6, price: 210 },
          { row: 'J', number: 7, price: 210 },
          { row: 'J', number: 8, price: 210 },
          { row: 'J', number: 9, price: 210 },
          { row: 'J', number: 10, price: 210 },
  
          { row: 'K', number: 1, price: 210 },
          { row: 'K', number: 2, price: 210 },
          { row: 'K', number: 3, price: 210 },
          { row: 'K', number: 4, price: 210 },
          { row: 'K', number: 5, price: 210 },
          { row: 'K', number: 6, price: 210 },
          { row: 'K', number: 7, price: 210 },
          { row: 'K', number: 8, price: 210 },
          { row: 'K', number: 9, price: 210 },
          { row: 'K', number: 10, price: 210 },
      ]
  }
];

const populateSeats = async () => {
  for (const show of shows) {
    const showRef = db.collection('shows').doc(show.showId);
    const seats = [...show.classicSeats, ...show.primeSeats];

    for (const seat of seats) {
      await showRef.collection('seats').add({
        row: seat.row,
        number: seat.number,
        price: seat.price,
        status: 'available'
      });
    }
  }
  console.log('Firestore has been populated with seat data.');
};

populateSeats().catch(console.error);
